config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get '/task/new', to: 'tasks#new', as: :new_task
post '/tasks', to: 'tasks#create', as: :create_task

get 'tasks/', to: 'tasks#index'
get 'tasks/:id', to: 'tasks#show', as: :show_task

get 'tasks/edit/:id', to: 'tasks#edit'
patch 'tasks/edit/:id', to: 'tasks#update'

delete 'tasks/:id', to: 'tasks#destroy'
  # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def update
  end

  def edit
  end

  def destroy
    @task.destroy
    redirect to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>task.title</h1>
<% form_for @task do |f| -%>
  <%= check_box_tag(:completed) %>
  <%= label_tag(:completed, "This task is complete) %>
<% end -%>
<% end -%>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<% @tasks.each do |task| %>
<h5><%= task.completed %> <%= link_to task.title, show_task_path(task) %></h5>
<% end %>
<%= link_to "create new task", new_task_path(@task)  %>

app/views/tasks/new.html.erb
<h1>New task</h1>
  <%= form_for @task do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title%>
  <%= f.label :details  %>
  <%= f.text_field :details%>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title  %></h1>
<h2><%= @task.details %></h2>
<h3><%= @task.completed %></h3>